# Use postgres/example user/password credentials
version: '3.1'

services:
  game:
    restart: always
    image: maven:3.6.2-jdk-8
    working_dir: /app
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    depends_on:
      - db
    ports:
      - "8081:8080"
    command: mvn clean spring-boot:run
  db:
    image: postgres:12.0
    restart: always
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
#      POSTGRES_USER: root
      POSTGRES_DB: game_server

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080