# Use postgres/example user/password credentials
version: '3.1'

services:
  game:
    restart: always
    image: gradle:5.6.3-jdk8
    working_dir: /app
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
      - ~/.gradle:/root/.gradle
    depends_on:
      - db
    ports:
      - "8081:8080"
    command: gradle bootRun
  db:
    image: postgres:12.0
    restart: always
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
#      POSTGRES_USER: root
      POSTGRES_DB: game_server

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080