version: "3.7"
services:
  pg_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: liushun
    ports:
      - 5432:5432