// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

package cn.balalals.gserver.protobuf;

public interface LogoutOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Logout)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string time = 1;</code>
     *
     * @return The time.
     */
    java.lang.String getTime();

    /**
     * <code>string time = 1;</code>
     *
     * @return The bytes for time.
     */
    com.google.protobuf.ByteString
    getTimeBytes();
}
