// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

package cn.balalals.gserver.protobuf;

/**
 * Protobuf type {@code Msg}
 */
public final class Msg extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Msg)
        MsgOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use Msg.newBuilder() to construct.
    private Msg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private Msg() {
        msgType_ = 0;
        content_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
        return new Msg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    private Msg(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 8: {
                        int rawValue = input.readEnum();

                        msgType_ = rawValue;
                        break;
                    }
                    case 18: {

                        content_ = input.readBytes();
                        break;
                    }
                    default: {
                        if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return cn.balalals.gserver.protobuf.MsgOuterClass.internal_static_Msg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return cn.balalals.gserver.protobuf.MsgOuterClass.internal_static_Msg_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        cn.balalals.gserver.protobuf.Msg.class, cn.balalals.gserver.protobuf.Msg.Builder.class);
    }

    public static final int MSGTYPE_FIELD_NUMBER = 1;
    private int msgType_;

    /**
     * <code>.MsgType msgType = 1;</code>
     *
     * @return The enum numeric value on the wire for msgType.
     */
    public int getMsgTypeValue() {
        return msgType_;
    }

    /**
     * <code>.MsgType msgType = 1;</code>
     *
     * @return The msgType.
     */
    public cn.balalals.gserver.protobuf.MsgType getMsgType() {
        @SuppressWarnings("deprecation")
        cn.balalals.gserver.protobuf.MsgType result = cn.balalals.gserver.protobuf.MsgType.valueOf(msgType_);
        return result == null ? cn.balalals.gserver.protobuf.MsgType.UNRECOGNIZED : result;
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString content_;

    /**
     * <code>bytes content = 2;</code>
     *
     * @return The content.
     */
    public com.google.protobuf.ByteString getContent() {
        return content_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (msgType_ != cn.balalals.gserver.protobuf.MsgType.LOGIN.getNumber()) {
            output.writeEnum(1, msgType_);
        }
        if (!content_.isEmpty()) {
            output.writeBytes(2, content_);
        }
        unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (msgType_ != cn.balalals.gserver.protobuf.MsgType.LOGIN.getNumber()) {
            size += com.google.protobuf.CodedOutputStream
                    .computeEnumSize(1, msgType_);
        }
        if (!content_.isEmpty()) {
            size += com.google.protobuf.CodedOutputStream
                    .computeBytesSize(2, content_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof cn.balalals.gserver.protobuf.Msg)) {
            return super.equals(obj);
        }
        cn.balalals.gserver.protobuf.Msg other = (cn.balalals.gserver.protobuf.Msg) obj;

        if (msgType_ != other.msgType_) return false;
        if (!getContent()
                .equals(other.getContent())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
        hash = (53 * hash) + msgType_;
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static cn.balalals.gserver.protobuf.Msg parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static cn.balalals.gserver.protobuf.Msg parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static cn.balalals.gserver.protobuf.Msg parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static cn.balalals.gserver.protobuf.Msg parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static cn.balalals.gserver.protobuf.Msg parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static cn.balalals.gserver.protobuf.Msg parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static cn.balalals.gserver.protobuf.Msg parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static cn.balalals.gserver.protobuf.Msg parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cn.balalals.gserver.protobuf.Msg parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static cn.balalals.gserver.protobuf.Msg parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static cn.balalals.gserver.protobuf.Msg parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static cn.balalals.gserver.protobuf.Msg parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(cn.balalals.gserver.protobuf.Msg prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code Msg}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:Msg)
            cn.balalals.gserver.protobuf.MsgOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return cn.balalals.gserver.protobuf.MsgOuterClass.internal_static_Msg_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return cn.balalals.gserver.protobuf.MsgOuterClass.internal_static_Msg_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            cn.balalals.gserver.protobuf.Msg.class, cn.balalals.gserver.protobuf.Msg.Builder.class);
        }

        // Construct using cn.balalals.im.protobuf.Msg.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            msgType_ = 0;

            content_ = com.google.protobuf.ByteString.EMPTY;

            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return cn.balalals.gserver.protobuf.MsgOuterClass.internal_static_Msg_descriptor;
        }

        @java.lang.Override
        public cn.balalals.gserver.protobuf.Msg getDefaultInstanceForType() {
            return cn.balalals.gserver.protobuf.Msg.getDefaultInstance();
        }

        @java.lang.Override
        public cn.balalals.gserver.protobuf.Msg build() {
            cn.balalals.gserver.protobuf.Msg result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public cn.balalals.gserver.protobuf.Msg buildPartial() {
            cn.balalals.gserver.protobuf.Msg result = new cn.balalals.gserver.protobuf.Msg(this);
            result.msgType_ = msgType_;
            result.content_ = content_;
            onBuilt();
            return result;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof cn.balalals.gserver.protobuf.Msg) {
                return mergeFrom((cn.balalals.gserver.protobuf.Msg) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(cn.balalals.gserver.protobuf.Msg other) {
            if (other == cn.balalals.gserver.protobuf.Msg.getDefaultInstance()) return this;
            if (other.msgType_ != 0) {
                setMsgTypeValue(other.getMsgTypeValue());
            }
            if (other.getContent() != com.google.protobuf.ByteString.EMPTY) {
                setContent(other.getContent());
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            cn.balalals.gserver.protobuf.Msg parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (cn.balalals.gserver.protobuf.Msg) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private int msgType_ = 0;

        /**
         * <code>.MsgType msgType = 1;</code>
         *
         * @return The enum numeric value on the wire for msgType.
         */
        public int getMsgTypeValue() {
            return msgType_;
        }

        /**
         * <code>.MsgType msgType = 1;</code>
         *
         * @param value The enum numeric value on the wire for msgType to set.
         * @return This builder for chaining.
         */
        public Builder setMsgTypeValue(int value) {
            msgType_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>.MsgType msgType = 1;</code>
         *
         * @return The msgType.
         */
        public cn.balalals.gserver.protobuf.MsgType getMsgType() {
            @SuppressWarnings("deprecation")
            cn.balalals.gserver.protobuf.MsgType result = cn.balalals.gserver.protobuf.MsgType.valueOf(msgType_);
            return result == null ? cn.balalals.gserver.protobuf.MsgType.UNRECOGNIZED : result;
        }

        /**
         * <code>.MsgType msgType = 1;</code>
         *
         * @param value The msgType to set.
         * @return This builder for chaining.
         */
        public Builder setMsgType(cn.balalals.gserver.protobuf.MsgType value) {
            if (value == null) {
                throw new NullPointerException();
            }

            msgType_ = value.getNumber();
            onChanged();
            return this;
        }

        /**
         * <code>.MsgType msgType = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearMsgType() {

            msgType_ = 0;
            onChanged();
            return this;
        }

        private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;

        /**
         * <code>bytes content = 2;</code>
         *
         * @return The content.
         */
        public com.google.protobuf.ByteString getContent() {
            return content_;
        }

        /**
         * <code>bytes content = 2;</code>
         *
         * @param value The content to set.
         * @return This builder for chaining.
         */
        public Builder setContent(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }

            content_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>bytes content = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearContent() {

            content_ = getDefaultInstance().getContent();
            onChanged();
            return this;
        }

        @java.lang.Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:Msg)
    }

    // @@protoc_insertion_point(class_scope:Msg)
    private static final cn.balalals.gserver.protobuf.Msg DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new cn.balalals.gserver.protobuf.Msg();
    }

    public static cn.balalals.gserver.protobuf.Msg getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Msg>
            PARSER = new com.google.protobuf.AbstractParser<Msg>() {
        @java.lang.Override
        public Msg parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new Msg(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<Msg> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Msg> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public cn.balalals.gserver.protobuf.Msg getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

