// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

package cn.balalals.gserver.protobuf;

public final class MsgOuterClass {
    private MsgOuterClass() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Msg_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Msg_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_LoginMsg_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_LoginMsg_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_LogoutMsg_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_LogoutMsg_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\tmsg.proto\"1\n\003Msg\022\031\n\007msgType\030\001 \001(\0162\010.Ms" +
                        "gType\022\017\n\007content\030\002 \001(\014\"-\n\010LoginMsg\022\017\n\007ac" +
                        "count\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"\031\n\tLogoutM" +
                        "sg\022\014\n\004time\030\001 \001(\t* \n\007MsgType\022\t\n\005LOGIN\020\000\022\n" +
                        "\n\006LOGOUT\020\001B\033\n\027cn.balalals.im.protobufP\001b" +
                        "\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_Msg_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_Msg_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Msg_descriptor,
                new java.lang.String[]{"MsgType", "Content",});
        internal_static_LoginMsg_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_LoginMsg_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_LoginMsg_descriptor,
                new java.lang.String[]{"Account", "Password",});
        internal_static_LogoutMsg_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_LogoutMsg_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_LogoutMsg_descriptor,
                new java.lang.String[]{"Time",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
