// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

package cn.balalals.game_server.protobuf;

public interface LoginMsgOrBuilder extends
        // @@protoc_insertion_point(interface_extends:LoginMsg)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string account = 1;</code>
     *
     * @return The account.
     */
    java.lang.String getAccount();

    /**
     * <code>string account = 1;</code>
     *
     * @return The bytes for account.
     */
    com.google.protobuf.ByteString
    getAccountBytes();

    /**
     * <code>string password = 2;</code>
     *
     * @return The password.
     */
    java.lang.String getPassword();

    /**
     * <code>string password = 2;</code>
     *
     * @return The bytes for password.
     */
    com.google.protobuf.ByteString
    getPasswordBytes();
}
